spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/editor?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    base-package: com.wosummer.demo
    table-prefix: t_
    id-type: AUTO
    tables: "t_article,t_user,t_invitecode,t_kind_tag,t_mission,t_m_template,t_mp_record,t_notice,t_record,t_repeat_rate_check,t_tag,t_tt_account"
